apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql-secret
  labels:
    app: wordpress
type: Opaque
data:
  # Base64 encoded values
  mysql-root-password: Your encrypted text
  mysql-password: Your encrypted text
  mysql-database: Your encrypted text
  mysql-user: Your encrypted text
